title: Project Portfolio
logo: /assets/img/pfp.png
description: Operational leader, software engineer and data analyst with over 12 years of experience in public health.  
show_downloads: false
theme: jekyll-theme-minimal
