title: Project Portfolio
logo: /assets/img/pfp.png
description: Operational leader with over 12 years of experience in public health. 
Possessing a unique blend of healthcare expertise and technical acumen. Skye has a proven track record of improving data reporting, clinical competencies, and service delivery. 
Skye has an academic background in Computer Science, having studied software engineering through The Open University. 
show_downloads: true
theme: jekyll-theme-minimal
